name: Feature request
description: Suggest a change or addition
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: What you would like it to do
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: What you do today instead
